//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtherBarberShop.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterHairdresser
    {
        public string NameRole { get; set; }
        public byte[] CodImage { get; set; }
        public string NamePaul { get; set; }
        public int PersonalNumberWorker { get; set; }
        public string SurnameWorker { get; set; }
        public string NameWorker { get; set; }
        public string MiddlenameWorker { get; set; }
        public string LoginWorker { get; set; }
        public string PasswordWorker { get; set; }
    }
}
