//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtherBarberShop.ModelFolder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OtherBarberShopDataBaseEntities : DbContext
    {
        public OtherBarberShopDataBaseEntities()
            : base("name=OtherBarberShopDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientTabel> ClientTabel { get; set; }
        public virtual DbSet<HaircutTable> HaircutTable { get; set; }
        public virtual DbSet<ImageWorkerTable> ImageWorkerTable { get; set; }
        public virtual DbSet<RecordTable> RecordTable { get; set; }
        public virtual DbSet<RoleTable> RoleTable { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<WorkerTable> WorkerTable { get; set; }
    }
}
