//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtherBarberShop.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordTable
    {
        public int PersonalNumberRecord { get; set; }
        public int PNWorkerRecord { get; set; }
        public int PNClientRecord { get; set; }
        public int PNHaircutRecord { get; set; }
        public System.DateTime DateRecord { get; set; }
        public System.TimeSpan TimeRecord { get; set; }
    
        public virtual ClientTabel ClientTabel { get; set; }
        public virtual HaircutTable HaircutTable { get; set; }
        public virtual WorkerTable WorkerTable { get; set; }
    }
}
