//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtherBarberShop.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkerTable()
        {
            this.RecordTable = new HashSet<RecordTable>();
        }
    
        public int PersonalNumberWorker { get; set; }
        public string SurnameWorker { get; set; }
        public string NameWorker { get; set; }
        public string MiddlenameWorker { get; set; }
        public int PNRoleWorker { get; set; }
        public int PNImageWorker { get; set; }
        public string LoginWorker { get; set; }
        public string PasswordWorker { get; set; }
        public int PNPaulWorker { get; set; }
    
        public virtual ImageWorkerTable ImageWorkerTable { get; set; }
        public virtual PaulTable PaulTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecordTable> RecordTable { get; set; }
        public virtual RoleTable RoleTable { get; set; }
    }
}
